### ISSUE TITLE
Can't setup the Main_game to start

### ISSUE THREAD

**Issue by dinhbinh599** [SciADV-Community/playthrough-bot#1]
Hi, i'm really interested in your bot, I was thinking of making a server for certain visual novels playthrough and found your bot. But I don't really know how to setting it up through commands, could you elaborate for me. So far i've added a game and set it to Main_game, but how do I set up the Start_category and Chapter_prefix? It seems that the $start command can't be used without those two. Also is there any command to delete an added game? And can more than one game have the appropriate role systems based on chapter? Or just one Main_game per server.

Thank you

**Comment by rainx0r** [comment]
Hey, sorry for the late reply.

Only 1 game can be a "Main_game", to which the "$chapter" command corresponds to. I might expand this in the future where you specify which game you completed the "$chapter" for, but the main issue is managing roles at that point.

To set up the Start_category and Archive_category, you also need to specify the game you want to set that for. For example, say the VN was "chaos;child", and the category ID was "1234567890", then the command you'd use, as an admin on the server, would be: `$admin set Start_category chaos;child 1234567890`.

To set the chapter / route prefix, you'd do: `$admin set Chapter_prefix Chapter` for example. You'd do the same for Route prefix. The bot looks for the Route prefixed roles when the argument to the `$chapter` command is alphanumeric.

No there is no command to delete an added game as of yet, I might look into it in the future.

I hope that answered your questions, albeit late, my apologies for that.

**Comment by rainx0r** [comment]
Stale & the entire bot is being rewritten into a system, closing.
